#!/bin/bash
#-------------------------------------------------------------------------------
#-- Compton toggle on/off
#-- Mindi @ Mindinet.org
#-- GNU General Public License v3.0
#-------------------------------------------------------------------------------

process=$(pgrep -xf ${1})

if [ "${process}" == "" ]; then
	${1} &
else
	killall ${1} &
fi
